services:
  app:
    build: .
    container_name: scratch
    command: python -m debugpy  --listen 0.0.0.0:5678 -m uvicorn app.main:app --port 80 --host 0.0.0.0  --log-level  debug --reload
    # command: uvicorn app.main:app --port 80 --host 0.0.0.0  --log-level  debug --reload
    ports:
      - 8080:80
      - 5678:5678
    volumes:
      - .:/app
    env_file: "app/.env"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
