name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flake8
      - name: Run Flake8
        run: |
          source venv/bin/activate
          flake8 .
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: ${#DOCKER_USERNAME}"
          echo "DOCKER_PASSWORD: ${#DOCKER_PASSWORD}"
          echo "VPS_HOST: ${#VPS_HOST}"
          echo "VPS_USER: ${#VPS_USER}"
          echo "VPS_SSH_KEY: ${#VPS_SSH_KEY}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Test Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/api_proxy_microservice:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER_GITHUB }}
          password: ${{ secrets.VPS_PASSWORD_GITHUB }}
          script: |
            cd ~/code/webinargeek_microservice
            git pull
            docker compose down
            docker compose up -d --build
