name: Test Secrets
on:
  push:
    branches:
      - develop
  workflow_dispatch:
permissions:
  contents: read # Default permission to read repository contents
  secrets: read # Ensure the workflow can read secrets
jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: ${#DOCKER_USERNAME}"
          echo "DOCKER_PASSWORD: ${#DOCKER_PASSWORD}"
          echo "VPS_HOST: ${#VPS_HOST}"
          echo "VPS_USER: ${#VPS_USER}"
          echo "VPS_SSH_KEY: ${#VPS_SSH_KEY}"
