name: Test Secrets
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Debug Secrets
        run: |
          echo ${{ secrets.TEST }} | sed -e 's/\(.\)/\1 /g'
          echo "Length ${ #secrets.TEST }}
          echo "This is the undefined variable: ${{ secrets.TEST_UNDEFINED }}
          
