# test
name: Test Secrets
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER_GITHUB }}
          password: ${{ secrets.VPS_PASSWORD_GITHUB }}
          script: echo "Hello World"
          # jobs:

#   test_secrets:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Debug Secrets
#         run: |
#           auth_token="${{ secrets.DOCKER_USERNAME }}"
#           echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
#           echo "DOCKER_USERNAME: ${#DOCKER_USERNAME}"
#           echo "DOCKER_PASSWORD: ${#DOCKER_PASSWORD}"
#           echo "VPS_HOST: ${#VPS_HOST}"
#           echo "VPS_USER: ${#VPS_USER}"
#           echo "VPS_SSH_KEY: ${#VPS_SSH_KEY}"
#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USER }}
#           key: ${{ secrets.VPS_KEY }}
#           script: "echo \"This runs on the vps\" "
