name: Test Secrets
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: ${# secrets.DOCKER_USERNAME }"
          echo "DOCKER_PASSWORD: ${# secrets.DOCKER_PASSWORD }"
          echo "VPS_HOST: ${# secrets.VPS_HOST }"
          echo "VPS_USER: ${# secrets.VPS_USER }"
          echo "VPS_SSH_KEY: ${# secrets.VPS_SSH_KEY }"
